# ============================================
# ??????? ????
# ============================================
spring.application.name=OnlineShop__CV
# ============================================
# ??????? ??????? PostgreSQL
# ============================================
spring.datasource.url=jdbc:postgresql://localhost:5432/OnlineShop__CV_DB
spring.datasource.username=postgres
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver
# ============================================
# ??????? JPA & Hibernate
# ============================================
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=update
# ???? ????? - SQL?? ?? ?? ????? ???? ???
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
# ============================================
# ??????? ???????? (??????? ??? ????)
# ============================================
logging.level.org.springframework=INFO
logging.level.net.moha=DEBUG  # ???? ????
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
jwt.secret=my-very-strong-secret-key-that-is-at-least-48-bytes-long-for-HS384
jwt.expirationMs=86400000
server.port=443
server.ssl.key-store=classpath:ssl/keystore.p12
server.ssl.key-store-password=mM@4960208074
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=MySSL
app.cors.allowed-origins=https://onlineshop.com
app.payment-gateway.zarinpal.base-url = https://payment.zarinpal.com/pg
app.payment-gateway.zarinpal.merchant-id = xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
app.payment-gateway.zarinpal.callback-url = https://127.0.0.1/verify
app.payment-gateway.zarinpal.ipg-url = https://payment.zarinpal.com/pg/StartPay

#==============================================================================

